---
title: "Milestone_2"
author: "James Hutt"
date: "14/02/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## A review of two of last semester's projects

### [Strava Leaderboards](https://ddeuel.shinyapps.io/strava-leaderboards/)
Pros:
This project is interesting for the way it combines different types of data, notably spatial and timing data. The addition of the map makes it easier to see context and the dropdown menu makes navigation easy. For someone who is strava obsessed (which I am) its a fun way to play around with large amounts of data. The choice of plot, with individual data points visible, is appropriate as you can see both shape and amount of data present. 

Cons:
The scales on the slider bars are slightly offputting as they are not round numbers. Additionally the inclusion of a linear regression coefficient seems strange given the point of the results is that the relationship is highly non linear. Given that Strava and Google both allow interaction by APIs it would, it seems, have been possible to add more routes/activities easily which would have added to the richness of the project. 


### [Social Connectedness in America](https://bridger-gordon.shinyapps.io/FacebookSocialConnectedness/)
Pros:
This project is highly engaging. The data is compelling itself and well presented to make it easy to explore and reach genuinely novel results. I imagine many people would be intrigued to find out how states socially relate to each other too. The data and entire app is smartly presented and easy to navigate. A huge amount of data appears to have been collected and cleaned as the number of options which it is possible to modify in each plot is large - possibly to the point of overwhelming. The highlighting of a few key takeaway charts on the first page is a nice solution to this. 

Cons: 
Given the extremely large number of options available, particularly on the Demographic Correlations page it would have been nice to have more explanation. The axis labels to not immediately make it clear what each data point represents, making it hard to pull the most information for the charts. Compared to the first page, these charts are also less attractively formatted which is noticeable. Finally, on the Geographic Closeness page, the states are presented with number of counties in the histogram, this makes large states such as Texas jump out inappropriately. If the question is assessing the importance of geographic closeness then a proportion measure would seem more suitable than an absolute number. 

